document.write( '<html lang=\"en\">\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <title>Title</title>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '<div class=\"something\" style=\" height:100vh; background: url(\'https://i.stack.imgur.com/sxAz0.jpg\')\">\n' );
document.write( '    sdfsdfas sadfa sdf sad asdf asdf sadf as fd sdfsdfas sadfa sdf sad asdf asdf sadf as fdsdfsdfas sadfa sdf sad asdf\n' );
document.write( '    asdf sadf as fdsdfsdfas sadfa sdf sad asdf asdf sadf as fdsdfsdfas sadfa sdf sad asdf asdf sadf as fdsdfsdfas sadfa\n' );
document.write( '    sdf sad asdf asdf sadf as fdsdfsdfas sadfa sdf sad asdf asdf sadf as fd\n' );
document.write( '    <!--Копировать отсюда-->\n' );
document.write( '    <div class=\"popup_holder\">\n' );
document.write( '        <div class=\"blur\"></div>\n' );
document.write( '        <div class=\"popup_info_container\">\n' );
document.write( '            <div class=\"popup_info_holder\">\n' );
document.write( '                <h2 class=\"popup_header\">Some important questions?</h2>\n' );
document.write( '                <p class=\"popup_description\">Should i press the button or not</p>\n' );
document.write( '                <div class=\"popup_container\">\n' );
document.write( '                    <!--<a class=\"popup_button popup_button-yes\" href=\"/somewhere\">Yes</a>-->\n' );
document.write( '                    <!--<a class=\"popup_button popup_button-no\" href=\"/somewhere_else\">No</a>-->\n' );
document.write( '                    <!--Большая кнопка-->\n' );
document.write( '                    <a class=\"popup_button popup_button-big\" href=\"/somewhere_else\">YES</a>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '    <style>\n' );
document.write( '        .popup_holder * {\n' );
document.write( '            text-decoration: none;\n' );
document.write( '        }\n' );
document.write( '        .popup_holder {\n' );
document.write( '            z-index: 9999;\n' );
document.write( '            display: none;\n' );
document.write( '            /*display: flex;*/\n' );
document.write( '            position: fixed;\n' );
document.write( '            top:0;\n' );
document.write( '            left:0;\n' );
document.write( '            height: 100vh;\n' );
document.write( '            width: 100%;\n' );
document.write( '            backdrop-filter:blur(5px);\n' );
document.write( '            justify-content: center;\n' );
document.write( '            align-items: center;\n' );
document.write( '        }\n' );
document.write( '        .popup_info_holder {\n' );
document.write( '            min-width: 300px;\n' );
document.write( '            width: 50%;\n' );
document.write( '            padding: 20px;\n' );
document.write( '            padding-bottom: 40px;\n' );
document.write( '            background: #ffffff;\n' );
document.write( '            text-align: center;\n' );
document.write( '            border: 5px solid #8A8A8A;\n' );
document.write( '        }\n' );
document.write( '        .popup_container {\n' );
document.write( '            z-index: 100;\n' );
document.write( '            display: flex;\n' );
document.write( '            justify-content: space-around;\n' );
document.write( '            padding-top: 40px;\n' );
document.write( '        }\n' );
document.write( '        .popup_button {\n' );
document.write( '            padding:10px 30px;\n' );
document.write( '            min-width: 100px;\n' );
document.write( '            background: #e60505;\n' );
document.write( '            border: none;\n' );
document.write( '            font-family: Lato;\n' );
document.write( '            font-style: normal;\n' );
document.write( '            font-weight: bold;\n' );
document.write( '            font-size: 24px;\n' );
document.write( '            text-align: center;\n' );
document.write( '            color: #FAFAFF;\n' );
document.write( '            border-radius: 5px;;\n' );
document.write( '        }\n' );
document.write( '        .popup_button-big {\n' );
document.write( '            padding:20px 40px;\n' );
document.write( '        }\n' );
document.write( '        .popup_button-yes {\n' );
document.write( '            background: #6be67e;\n' );
document.write( '        }\n' );
document.write( '        .popup_button-no {\n' );
document.write( '            background: #e60505;\n' );
document.write( '        }\n' );
document.write( '        .popup_info_container {\n' );
document.write( '            z-index: 100;\n' );
document.write( '            position: absolute;\n' );
document.write( '            width: 100%;\n' );
document.write( '            height: 100%;\n' );
document.write( '            left:0;\n' );
document.write( '            top:0;\n' );
document.write( '            display: flex;\n' );
document.write( '            justify-content: center;\n' );
document.write( '            align-items: center;\n' );
document.write( '        }\n' );
document.write( '        .blur {\n' );
document.write( '            z-index: 80;\n' );
document.write( '            position: absolute;\n' );
document.write( '            width: 100%;\n' );
document.write( '            height: 100%;\n' );
document.write( '            left: 0;\n' );
document.write( '            top: 0;\n' );
document.write( '            background: rgba(0, 0, 0, 0.95);\n' );
document.write( '        }\n' );
document.write( '    </style>\n' );
document.write( '    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n' );
document.write( '    <script>\n' );
document.write( '\n' );
document.write( '        $(document).ready(function(){\n' );
document.write( '            var strGET = window.location.search.replace( \'?\', \'\');\n' );
document.write( '            var strSetup = \"user_true\";\n' );
document.write( '            if(!strGET.includes(strSetup)){\n' );
document.write( '             $(\".popup_holder\").css(\"display\",\"flex\");}\n' );
document.write( '            else {\n' );
document.write( '                console.log(1);\n' );
document.write( '            }\n' );
document.write( '        });\n' );
document.write( '    </script>\n' );
document.write( '   </div>\n' );
document.write( '</body>\n' );
document.write( '</html>' );
